version: '3.9'

services:
  test-app:
    image: node:18-alpine
    command: sh -c "apk add opus-tools git && git config --global --add safe.directory /test-app && npm install -g pnpm && pnpm i --frozen-lockfile && pnpm dev"
    env_file:
      - .test.env
    working_dir: /test-app
    volumes:
      - ./:/test-app
    depends_on:
      - test-db-postgres

  test-db-postgres:
    image: postgres:15-alpine
    env_file:
      - .test.env
